### PR TITLE
Rename Tournament module to TournamentSystem,

### PR DESCRIPTION
**Pull request by pawelma**
Tournament is too generic name.

### CODE REVIEW

**Comment by BenjaminSchaaf** [comment]
Thanks for the pull request. I completely agree that `Tournament` is too generic, but I have some issues with the proposed changes:

* Folder names should follow the same naming schema as ruby, thus `tournament_system` is preferred over `tournament-system`.
* `TournamentSystemSystem` is not an OK name, it should really be just `TournamentSystem`
* It doesn't pass rubocop.

**Comment by BenjaminSchaaf** [comment]
I've made these changes myself. This will require a major version increment to stay in-line with Semantic versioning.

**Comment by pawelmadejskikreditech** [comment]
Yep major bump is required in did.

Sorry that I didn't manage to fix the code but I was overwhelmed with other stuff. Thanks for update tho.

**Comment by BenjaminSchaaf** [comment]
No worries. May I ask what you're using this gem for? It would be nice to know :)

**Comment by pawelmadejskikreditech** [comment]
I was working on small chess project and I used this for tournaments pairing (using swiss::dutch method).

**Comment by BenjaminSchaaf** [comment]
Awesome. It's nice to know my work has been useful to others. Thanks for sharing. 

If you've got some thoughts on how to improve this library (or anything really), do feel free to add an issue.

**Comment by pawelmadejskikreditech** [comment]
OK. Will do.

**Pull request closed without merging**
